/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DevnetTestRouteImport } from './routes/devnet-test'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as BusinessPlanRouteImport } from './routes/business-plan'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorIndexRouteImport } from './routes/advisor.index'
import { Route as VaultIdRouteImport } from './routes/vault.$id'
import { Route as SignupKycRouteImport } from './routes/signup_.kyc'
import { Route as FundsHistoryRouteImport } from './routes/funds.history'
import { Route as FundsAddRouteImport } from './routes/funds.add'
import { Route as AdvisorSignupRouteImport } from './routes/advisor.signup'
import { Route as AdvisorProfileRouteImport } from './routes/advisor.profile'
import { Route as AdvisorMessagesRouteImport } from './routes/advisor.messages'
import { Route as AdvisorLoginRouteImport } from './routes/advisor.login'
import { Route as AdvisorDashboardRouteImport } from './routes/advisor.dashboard'
import { Route as AdminRampsRouteImport } from './routes/admin.ramps'
import { Route as AdminLedgerRouteImport } from './routes/admin.ledger'
import { Route as ApiPublicPaytrieWebhookRouteImport } from './routes/api/public/paytrie-webhook'
import { Route as AdvisorClientsClientIdRouteImport } from './routes/advisor.clients.$clientId'
import { Route as AdvisorClientsClientIdVaultVaultIdRouteImport } from './routes/advisor.clients.$clientId.vault.$vaultId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DevnetTestRoute = DevnetTestRouteImport.update({
  id: '/devnet-test',
  path: '/devnet-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessPlanRoute = BusinessPlanRouteImport.update({
  id: '/business-plan',
  path: '/business-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorIndexRoute = AdvisorIndexRouteImport.update({
  id: '/advisor/',
  path: '/advisor/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIdRoute = VaultIdRouteImport.update({
  id: '/vault/$id',
  path: '/vault/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupKycRoute = SignupKycRouteImport.update({
  id: '/signup_/kyc',
  path: '/signup/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsHistoryRoute = FundsHistoryRouteImport.update({
  id: '/funds/history',
  path: '/funds/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FundsAddRoute = FundsAddRouteImport.update({
  id: '/funds/add',
  path: '/funds/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorSignupRoute = AdvisorSignupRouteImport.update({
  id: '/advisor/signup',
  path: '/advisor/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorProfileRoute = AdvisorProfileRouteImport.update({
  id: '/advisor/profile',
  path: '/advisor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorMessagesRoute = AdvisorMessagesRouteImport.update({
  id: '/advisor/messages',
  path: '/advisor/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorLoginRoute = AdvisorLoginRouteImport.update({
  id: '/advisor/login',
  path: '/advisor/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorDashboardRoute = AdvisorDashboardRouteImport.update({
  id: '/advisor/dashboard',
  path: '/advisor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRampsRoute = AdminRampsRouteImport.update({
  id: '/admin/ramps',
  path: '/admin/ramps',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLedgerRoute = AdminLedgerRouteImport.update({
  id: '/admin/ledger',
  path: '/admin/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaytrieWebhookRoute = ApiPublicPaytrieWebhookRouteImport.update({
  id: '/api/public/paytrie-webhook',
  path: '/api/public/paytrie-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorClientsClientIdRoute = AdvisorClientsClientIdRouteImport.update({
  id: '/advisor/clients/$clientId',
  path: '/advisor/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorClientsClientIdVaultVaultIdRoute =
  AdvisorClientsClientIdVaultVaultIdRouteImport.update({
    id: '/vault/$vaultId',
    path: '/vault/$vaultId',
    getParentRoute: () => AdvisorClientsClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/business-plan': typeof BusinessPlanRoute
  '/claim': typeof ClaimRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/devnet-test': typeof DevnetTestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/ramps': typeof AdminRampsRoute
  '/advisor/dashboard': typeof AdvisorDashboardRoute
  '/advisor/login': typeof AdvisorLoginRoute
  '/advisor/messages': typeof AdvisorMessagesRoute
  '/advisor/profile': typeof AdvisorProfileRoute
  '/advisor/signup': typeof AdvisorSignupRoute
  '/funds/add': typeof FundsAddRoute
  '/funds/history': typeof FundsHistoryRoute
  '/signup/kyc': typeof SignupKycRoute
  '/vault/$id': typeof VaultIdRoute
  '/advisor/': typeof AdvisorIndexRoute
  '/advisor/clients/$clientId': typeof AdvisorClientsClientIdRouteWithChildren
  '/api/public/paytrie-webhook': typeof ApiPublicPaytrieWebhookRoute
  '/advisor/clients/$clientId/vault/$vaultId': typeof AdvisorClientsClientIdVaultVaultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/business-plan': typeof BusinessPlanRoute
  '/claim': typeof ClaimRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/devnet-test': typeof DevnetTestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/ramps': typeof AdminRampsRoute
  '/advisor/dashboard': typeof AdvisorDashboardRoute
  '/advisor/login': typeof AdvisorLoginRoute
  '/advisor/messages': typeof AdvisorMessagesRoute
  '/advisor/profile': typeof AdvisorProfileRoute
  '/advisor/signup': typeof AdvisorSignupRoute
  '/funds/add': typeof FundsAddRoute
  '/funds/history': typeof FundsHistoryRoute
  '/signup/kyc': typeof SignupKycRoute
  '/vault/$id': typeof VaultIdRoute
  '/advisor': typeof AdvisorIndexRoute
  '/advisor/clients/$clientId': typeof AdvisorClientsClientIdRouteWithChildren
  '/api/public/paytrie-webhook': typeof ApiPublicPaytrieWebhookRoute
  '/advisor/clients/$clientId/vault/$vaultId': typeof AdvisorClientsClientIdVaultVaultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/business-plan': typeof BusinessPlanRoute
  '/claim': typeof ClaimRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/devnet-test': typeof DevnetTestRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/ledger': typeof AdminLedgerRoute
  '/admin/ramps': typeof AdminRampsRoute
  '/advisor/dashboard': typeof AdvisorDashboardRoute
  '/advisor/login': typeof AdvisorLoginRoute
  '/advisor/messages': typeof AdvisorMessagesRoute
  '/advisor/profile': typeof AdvisorProfileRoute
  '/advisor/signup': typeof AdvisorSignupRoute
  '/funds/add': typeof FundsAddRoute
  '/funds/history': typeof FundsHistoryRoute
  '/signup_/kyc': typeof SignupKycRoute
  '/vault/$id': typeof VaultIdRoute
  '/advisor/': typeof AdvisorIndexRoute
  '/advisor/clients/$clientId': typeof AdvisorClientsClientIdRouteWithChildren
  '/api/public/paytrie-webhook': typeof ApiPublicPaytrieWebhookRoute
  '/advisor/clients/$clientId/vault/$vaultId': typeof AdvisorClientsClientIdVaultVaultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/business-plan'
    | '/claim'
    | '/create'
    | '/dashboard'
    | '/devnet-test'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/reset-password'
    | '/signup'
    | '/admin/ledger'
    | '/admin/ramps'
    | '/advisor/dashboard'
    | '/advisor/login'
    | '/advisor/messages'
    | '/advisor/profile'
    | '/advisor/signup'
    | '/funds/add'
    | '/funds/history'
    | '/signup/kyc'
    | '/vault/$id'
    | '/advisor/'
    | '/advisor/clients/$clientId'
    | '/api/public/paytrie-webhook'
    | '/advisor/clients/$clientId/vault/$vaultId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/business-plan'
    | '/claim'
    | '/create'
    | '/dashboard'
    | '/devnet-test'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/reset-password'
    | '/signup'
    | '/admin/ledger'
    | '/admin/ramps'
    | '/advisor/dashboard'
    | '/advisor/login'
    | '/advisor/messages'
    | '/advisor/profile'
    | '/advisor/signup'
    | '/funds/add'
    | '/funds/history'
    | '/signup/kyc'
    | '/vault/$id'
    | '/advisor'
    | '/advisor/clients/$clientId'
    | '/api/public/paytrie-webhook'
    | '/advisor/clients/$clientId/vault/$vaultId'
  id:
    | '__root__'
    | '/'
    | '/business-plan'
    | '/claim'
    | '/create'
    | '/dashboard'
    | '/devnet-test'
    | '/forgot-password'
    | '/login'
    | '/messages'
    | '/reset-password'
    | '/signup'
    | '/admin/ledger'
    | '/admin/ramps'
    | '/advisor/dashboard'
    | '/advisor/login'
    | '/advisor/messages'
    | '/advisor/profile'
    | '/advisor/signup'
    | '/funds/add'
    | '/funds/history'
    | '/signup_/kyc'
    | '/vault/$id'
    | '/advisor/'
    | '/advisor/clients/$clientId'
    | '/api/public/paytrie-webhook'
    | '/advisor/clients/$clientId/vault/$vaultId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BusinessPlanRoute: typeof BusinessPlanRoute
  ClaimRoute: typeof ClaimRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  DevnetTestRoute: typeof DevnetTestRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AdminLedgerRoute: typeof AdminLedgerRoute
  AdminRampsRoute: typeof AdminRampsRoute
  AdvisorDashboardRoute: typeof AdvisorDashboardRoute
  AdvisorLoginRoute: typeof AdvisorLoginRoute
  AdvisorMessagesRoute: typeof AdvisorMessagesRoute
  AdvisorProfileRoute: typeof AdvisorProfileRoute
  AdvisorSignupRoute: typeof AdvisorSignupRoute
  FundsAddRoute: typeof FundsAddRoute
  FundsHistoryRoute: typeof FundsHistoryRoute
  SignupKycRoute: typeof SignupKycRoute
  VaultIdRoute: typeof VaultIdRoute
  AdvisorIndexRoute: typeof AdvisorIndexRoute
  AdvisorClientsClientIdRoute: typeof AdvisorClientsClientIdRouteWithChildren
  ApiPublicPaytrieWebhookRoute: typeof ApiPublicPaytrieWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devnet-test': {
      id: '/devnet-test'
      path: '/devnet-test'
      fullPath: '/devnet-test'
      preLoaderRoute: typeof DevnetTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-plan': {
      id: '/business-plan'
      path: '/business-plan'
      fullPath: '/business-plan'
      preLoaderRoute: typeof BusinessPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/': {
      id: '/advisor/'
      path: '/advisor'
      fullPath: '/advisor/'
      preLoaderRoute: typeof AdvisorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$id': {
      id: '/vault/$id'
      path: '/vault/$id'
      fullPath: '/vault/$id'
      preLoaderRoute: typeof VaultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup_/kyc': {
      id: '/signup_/kyc'
      path: '/signup/kyc'
      fullPath: '/signup/kyc'
      preLoaderRoute: typeof SignupKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds/history': {
      id: '/funds/history'
      path: '/funds/history'
      fullPath: '/funds/history'
      preLoaderRoute: typeof FundsHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/funds/add': {
      id: '/funds/add'
      path: '/funds/add'
      fullPath: '/funds/add'
      preLoaderRoute: typeof FundsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/signup': {
      id: '/advisor/signup'
      path: '/advisor/signup'
      fullPath: '/advisor/signup'
      preLoaderRoute: typeof AdvisorSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/profile': {
      id: '/advisor/profile'
      path: '/advisor/profile'
      fullPath: '/advisor/profile'
      preLoaderRoute: typeof AdvisorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/messages': {
      id: '/advisor/messages'
      path: '/advisor/messages'
      fullPath: '/advisor/messages'
      preLoaderRoute: typeof AdvisorMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/login': {
      id: '/advisor/login'
      path: '/advisor/login'
      fullPath: '/advisor/login'
      preLoaderRoute: typeof AdvisorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/dashboard': {
      id: '/advisor/dashboard'
      path: '/advisor/dashboard'
      fullPath: '/advisor/dashboard'
      preLoaderRoute: typeof AdvisorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ramps': {
      id: '/admin/ramps'
      path: '/admin/ramps'
      fullPath: '/admin/ramps'
      preLoaderRoute: typeof AdminRampsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ledger': {
      id: '/admin/ledger'
      path: '/admin/ledger'
      fullPath: '/admin/ledger'
      preLoaderRoute: typeof AdminLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paytrie-webhook': {
      id: '/api/public/paytrie-webhook'
      path: '/api/public/paytrie-webhook'
      fullPath: '/api/public/paytrie-webhook'
      preLoaderRoute: typeof ApiPublicPaytrieWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/clients/$clientId': {
      id: '/advisor/clients/$clientId'
      path: '/advisor/clients/$clientId'
      fullPath: '/advisor/clients/$clientId'
      preLoaderRoute: typeof AdvisorClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/clients/$clientId/vault/$vaultId': {
      id: '/advisor/clients/$clientId/vault/$vaultId'
      path: '/vault/$vaultId'
      fullPath: '/advisor/clients/$clientId/vault/$vaultId'
      preLoaderRoute: typeof AdvisorClientsClientIdVaultVaultIdRouteImport
      parentRoute: typeof AdvisorClientsClientIdRoute
    }
  }
}

interface AdvisorClientsClientIdRouteChildren {
  AdvisorClientsClientIdVaultVaultIdRoute: typeof AdvisorClientsClientIdVaultVaultIdRoute
}

const AdvisorClientsClientIdRouteChildren: AdvisorClientsClientIdRouteChildren =
  {
    AdvisorClientsClientIdVaultVaultIdRoute:
      AdvisorClientsClientIdVaultVaultIdRoute,
  }

const AdvisorClientsClientIdRouteWithChildren =
  AdvisorClientsClientIdRoute._addFileChildren(
    AdvisorClientsClientIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BusinessPlanRoute: BusinessPlanRoute,
  ClaimRoute: ClaimRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  DevnetTestRoute: DevnetTestRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AdminLedgerRoute: AdminLedgerRoute,
  AdminRampsRoute: AdminRampsRoute,
  AdvisorDashboardRoute: AdvisorDashboardRoute,
  AdvisorLoginRoute: AdvisorLoginRoute,
  AdvisorMessagesRoute: AdvisorMessagesRoute,
  AdvisorProfileRoute: AdvisorProfileRoute,
  AdvisorSignupRoute: AdvisorSignupRoute,
  FundsAddRoute: FundsAddRoute,
  FundsHistoryRoute: FundsHistoryRoute,
  SignupKycRoute: SignupKycRoute,
  VaultIdRoute: VaultIdRoute,
  AdvisorIndexRoute: AdvisorIndexRoute,
  AdvisorClientsClientIdRoute: AdvisorClientsClientIdRouteWithChildren,
  ApiPublicPaytrieWebhookRoute: ApiPublicPaytrieWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
