/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DevnetTestRouteImport } from './routes/devnet-test'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateRouteImport } from './routes/create'
import { Route as ClaimRouteImport } from './routes/claim'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorIndexRouteImport } from './routes/advisor.index'
import { Route as VaultIdRouteImport } from './routes/vault.$id'
import { Route as AdvisorSignupRouteImport } from './routes/advisor.signup'
import { Route as AdvisorProfileRouteImport } from './routes/advisor.profile'
import { Route as AdvisorMessagesRouteImport } from './routes/advisor.messages'
import { Route as AdvisorLoginRouteImport } from './routes/advisor.login'
import { Route as AdvisorDashboardRouteImport } from './routes/advisor.dashboard'
import { Route as AdvisorClientClientIdRouteImport } from './routes/advisor.client.$clientId'
import { Route as AdvisorClientClientIdVaultVaultIdRouteImport } from './routes/advisor.client.$clientId.vault.$vaultId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevnetTestRoute = DevnetTestRouteImport.update({
  id: '/devnet-test',
  path: '/devnet-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRoute = ClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorIndexRoute = AdvisorIndexRouteImport.update({
  id: '/advisor/',
  path: '/advisor/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIdRoute = VaultIdRouteImport.update({
  id: '/vault/$id',
  path: '/vault/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorSignupRoute = AdvisorSignupRouteImport.update({
  id: '/advisor/signup',
  path: '/advisor/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorProfileRoute = AdvisorProfileRouteImport.update({
  id: '/advisor/profile',
  path: '/advisor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorMessagesRoute = AdvisorMessagesRouteImport.update({
  id: '/advisor/messages',
  path: '/advisor/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorLoginRoute = AdvisorLoginRouteImport.update({
  id: '/advisor/login',
  path: '/advisor/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorDashboardRoute = AdvisorDashboardRouteImport.update({
  id: '/advisor/dashboard',
  path: '/advisor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorClientClientIdRoute = AdvisorClientClientIdRouteImport.update({
  id: '/advisor/client/$clientId',
  path: '/advisor/client/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorClientClientIdVaultVaultIdRoute =
  AdvisorClientClientIdVaultVaultIdRouteImport.update({
    id: '/vault/$vaultId',
    path: '/vault/$vaultId',
    getParentRoute: () => AdvisorClientClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/devnet-test': typeof DevnetTestRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/signup': typeof SignupRoute
  '/advisor/dashboard': typeof AdvisorDashboardRoute
  '/advisor/login': typeof AdvisorLoginRoute
  '/advisor/messages': typeof AdvisorMessagesRoute
  '/advisor/profile': typeof AdvisorProfileRoute
  '/advisor/signup': typeof AdvisorSignupRoute
  '/vault/$id': typeof VaultIdRoute
  '/advisor/': typeof AdvisorIndexRoute
  '/advisor/client/$clientId': typeof AdvisorClientClientIdRouteWithChildren
  '/advisor/client/$clientId/vault/$vaultId': typeof AdvisorClientClientIdVaultVaultIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/devnet-test': typeof DevnetTestRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/signup': typeof SignupRoute
  '/advisor/dashboard': typeof AdvisorDashboardRoute
  '/advisor/login': typeof AdvisorLoginRoute
  '/advisor/messages': typeof AdvisorMessagesRoute
  '/advisor/profile': typeof AdvisorProfileRoute
  '/advisor/signup': typeof AdvisorSignupRoute
  '/vault/$id': typeof VaultIdRoute
  '/advisor': typeof AdvisorIndexRoute
  '/advisor/client/$clientId': typeof AdvisorClientClientIdRouteWithChildren
  '/advisor/client/$clientId/vault/$vaultId': typeof AdvisorClientClientIdVaultVaultIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/claim': typeof ClaimRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/devnet-test': typeof DevnetTestRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/signup': typeof SignupRoute
  '/advisor/dashboard': typeof AdvisorDashboardRoute
  '/advisor/login': typeof AdvisorLoginRoute
  '/advisor/messages': typeof AdvisorMessagesRoute
  '/advisor/profile': typeof AdvisorProfileRoute
  '/advisor/signup': typeof AdvisorSignupRoute
  '/vault/$id': typeof VaultIdRoute
  '/advisor/': typeof AdvisorIndexRoute
  '/advisor/client/$clientId': typeof AdvisorClientClientIdRouteWithChildren
  '/advisor/client/$clientId/vault/$vaultId': typeof AdvisorClientClientIdVaultVaultIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/claim'
    | '/create'
    | '/dashboard'
    | '/devnet-test'
    | '/login'
    | '/messages'
    | '/signup'
    | '/advisor/dashboard'
    | '/advisor/login'
    | '/advisor/messages'
    | '/advisor/profile'
    | '/advisor/signup'
    | '/vault/$id'
    | '/advisor/'
    | '/advisor/client/$clientId'
    | '/advisor/client/$clientId/vault/$vaultId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/claim'
    | '/create'
    | '/dashboard'
    | '/devnet-test'
    | '/login'
    | '/messages'
    | '/signup'
    | '/advisor/dashboard'
    | '/advisor/login'
    | '/advisor/messages'
    | '/advisor/profile'
    | '/advisor/signup'
    | '/vault/$id'
    | '/advisor'
    | '/advisor/client/$clientId'
    | '/advisor/client/$clientId/vault/$vaultId'
  id:
    | '__root__'
    | '/'
    | '/claim'
    | '/create'
    | '/dashboard'
    | '/devnet-test'
    | '/login'
    | '/messages'
    | '/signup'
    | '/advisor/dashboard'
    | '/advisor/login'
    | '/advisor/messages'
    | '/advisor/profile'
    | '/advisor/signup'
    | '/vault/$id'
    | '/advisor/'
    | '/advisor/client/$clientId'
    | '/advisor/client/$clientId/vault/$vaultId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClaimRoute: typeof ClaimRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  DevnetTestRoute: typeof DevnetTestRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  SignupRoute: typeof SignupRoute
  AdvisorDashboardRoute: typeof AdvisorDashboardRoute
  AdvisorLoginRoute: typeof AdvisorLoginRoute
  AdvisorMessagesRoute: typeof AdvisorMessagesRoute
  AdvisorProfileRoute: typeof AdvisorProfileRoute
  AdvisorSignupRoute: typeof AdvisorSignupRoute
  VaultIdRoute: typeof VaultIdRoute
  AdvisorIndexRoute: typeof AdvisorIndexRoute
  AdvisorClientClientIdRoute: typeof AdvisorClientClientIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devnet-test': {
      id: '/devnet-test'
      path: '/devnet-test'
      fullPath: '/devnet-test'
      preLoaderRoute: typeof DevnetTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim': {
      id: '/claim'
      path: '/claim'
      fullPath: '/claim'
      preLoaderRoute: typeof ClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/': {
      id: '/advisor/'
      path: '/advisor'
      fullPath: '/advisor/'
      preLoaderRoute: typeof AdvisorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$id': {
      id: '/vault/$id'
      path: '/vault/$id'
      fullPath: '/vault/$id'
      preLoaderRoute: typeof VaultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/signup': {
      id: '/advisor/signup'
      path: '/advisor/signup'
      fullPath: '/advisor/signup'
      preLoaderRoute: typeof AdvisorSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/profile': {
      id: '/advisor/profile'
      path: '/advisor/profile'
      fullPath: '/advisor/profile'
      preLoaderRoute: typeof AdvisorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/messages': {
      id: '/advisor/messages'
      path: '/advisor/messages'
      fullPath: '/advisor/messages'
      preLoaderRoute: typeof AdvisorMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/login': {
      id: '/advisor/login'
      path: '/advisor/login'
      fullPath: '/advisor/login'
      preLoaderRoute: typeof AdvisorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/dashboard': {
      id: '/advisor/dashboard'
      path: '/advisor/dashboard'
      fullPath: '/advisor/dashboard'
      preLoaderRoute: typeof AdvisorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/client/$clientId': {
      id: '/advisor/client/$clientId'
      path: '/advisor/client/$clientId'
      fullPath: '/advisor/client/$clientId'
      preLoaderRoute: typeof AdvisorClientClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/client/$clientId/vault/$vaultId': {
      id: '/advisor/client/$clientId/vault/$vaultId'
      path: '/vault/$vaultId'
      fullPath: '/advisor/client/$clientId/vault/$vaultId'
      preLoaderRoute: typeof AdvisorClientClientIdVaultVaultIdRouteImport
      parentRoute: typeof AdvisorClientClientIdRoute
    }
  }
}

interface AdvisorClientClientIdRouteChildren {
  AdvisorClientClientIdVaultVaultIdRoute: typeof AdvisorClientClientIdVaultVaultIdRoute
}

const AdvisorClientClientIdRouteChildren: AdvisorClientClientIdRouteChildren = {
  AdvisorClientClientIdVaultVaultIdRoute:
    AdvisorClientClientIdVaultVaultIdRoute,
}

const AdvisorClientClientIdRouteWithChildren =
  AdvisorClientClientIdRoute._addFileChildren(
    AdvisorClientClientIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClaimRoute: ClaimRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  DevnetTestRoute: DevnetTestRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  SignupRoute: SignupRoute,
  AdvisorDashboardRoute: AdvisorDashboardRoute,
  AdvisorLoginRoute: AdvisorLoginRoute,
  AdvisorMessagesRoute: AdvisorMessagesRoute,
  AdvisorProfileRoute: AdvisorProfileRoute,
  AdvisorSignupRoute: AdvisorSignupRoute,
  VaultIdRoute: VaultIdRoute,
  AdvisorIndexRoute: AdvisorIndexRoute,
  AdvisorClientClientIdRoute: AdvisorClientClientIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
